version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.0"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: build Docker image
          command: docker build . -t partyasterisk:$CIRCLE_BUILD_NUM

  deploy:
    docker:
      - image: buildpack-deps:bionic
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: install Heroku CLI
          command: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run:
         name: push the image to the registry and relese
         command: |
           heroku container:login
           heroku container:push web -a $HEROKU_APP_NAME
           heroku container:release web -a $HEROKU_APP_NAME

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
